### PR TITLE
Update to NH 5.2

### LINKED ISSUE #28: Support for latest version of NHibernate
..would be great!

### PR DESCRIPTION
**Pull request by jaykay-design**
Fixes #28

All test pass.

The only changes done were using the refactored logging interface of NH 5.1 and later. Unfortunately this is not backwards compatible,

### CODE REVIEW

**Comment by robdmoore** [comment]
Looks like there are some errors with this PR. If you are able to resolve I'm happy to merge and release.

**Comment by jaykay-design** [comment]
I have 0 experience with AppVeyor and don't know why it is not able to build the project. It seems to properly restore all required packages but then while building the project can't find them.
All test seem to pass locally though (clean build): 
image

**Comment by robdmoore** [comment]
Yeah - that's really odd behaviour.

The App Veyor config we use is https://github.com/MRCollective/AppVeyorConfig.

Any idea why this is hapening @MattDavies? It definitely looks like it resolve the nuget packages and then can't find them.

**Comment by jaykay-design** [comment]
Sorry .. I have closed the PR as I've worked on other stuff in my master branch. I know now that  I should have made a branch for this PR specifically, sorry, newbie mistake.

If you want I can make a new PR with a branch specifically for this.

**Pull request closed without merging**
