### PR TITLE
#20 Upgrading to NH 4.1.x

### PR DESCRIPTION
**Pull request by RogerKratz**
Added assembly redirect in test project due to NH ref in FluentNHibernate

### CODE REVIEW

**Comment by robdmoore** [comment]
You also need to adjust the nuspec file (https://github.com/MRCollective/NHibernate.SqlAzure/blob/master/NHibernate4.SqlAzure/NHibernate4.SqlAzure.nuspec) to update the dependency the package has

**Comment by RogerKratz** [comment]
Was a bit suprise to read
<<
A stable package release cannot have a pre-release dependency. This avoids accidentally installing a potentially unstable releases.
>>
(https://docs.nuget.org/ndocs/create-packages/prerelease-packages)

Probably easier to wait for stable release then. If not, this lib has to be set to pre-release as well.

Updated the pull request so it's good-to-go when a NHib stable release of 4.1 has been made.

**Comment by RogerKratz** [comment]
@robdmoore
NH 4.1 GA now released. This PR should be good-to-go now.

**Comment by RogerKratz** [comment]
ping! Do you need any more changes to merge this one?

**Comment by nemenos** [comment]
I'm waiting for this pull request to be accepted too

**Comment by robdmoore** [comment]
Sorry peeps - had a new kid a couple of months back so been hectic :P

**Pull request merged**
